### ISSUE TITLE
Drafts articles are shown in sitemap.xml

### ISSUE THREAD

**Issue by alexislefebvre** [Victoire/victoire#1009]
## Description

With Victoire 2.3, we can see some articles that have the _draft_ status in the sitemap.

## Resolution Ideas
Don't show draft articles in `sitemap.xml`.

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |   |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        | &#10004;         |
| Core           |          | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UI             |          |                |          |

Related to #923.

**Comment by lenybernard** [comment]
closed by https://github.com/Victoire/victoire/pull/1114
