### ISSUE TITLE
Modernizr is not defined

### ISSUE THREAD

**Issue by ckjet** [Victoire/victoire#1064]
## Description
After installation with guide get error in browser. "Modernizr is not defined"

## Resolution Ideas

Add include of Modernizr.
## Related to

| UI             |          |                |          |

**Comment by ckjet** [comment]
You can close issue, I selected another cms which worked.

**Comment by lenybernard** [comment]
This should work as there is an assetic-injector taf named modernizr here https://github.com/Victoire/victoire/blob/2.3/Bundle/CoreBundle/Resources/config/assetic_injector.json#L33 

... and loaded in layout here https://github.com/Victoire/victoire/blob/2.3/Bundle/CoreBundle/Resources/views/Layout/layout.html.twig#L20

I'd say, be sure to have correctly enabled the [AsseticInjectorBundle](https://github.com/Troopers/AsseticInjectorBundle)
