### ISSUE TITLE
Conflict between VictoireI18nBundle and JMSI18nRoutingBundle

### ISSUE THREAD

**Issue by lenybernard** [Victoire/victoire#123]
When both are installed, our router is not able to find the base route (eg. victoire_core_page_show).

**Comment by talbotseb** [comment]
Will this issue be deprecated once the 1.6 version will be out ?

**Comment by talbotseb** [comment]
@lenybernard is this issue still accurate with the evolution of Victoire, could you check and close it please ?

**Comment by alexislefebvre** [comment]
This problem has not appeared again.
