### ISSUE TITLE
Behat Tests : Impossible to create 2 blogs as ORM Fixtures

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#286]
# When I want to set up 2 blogs within the following file :

/Tests/Functionnal/src/Acme/AppBundle/DataFixtures/Fixtures/ORM/Blog/blog.yml
# I got this error whand i run the test using @aliceBlog) :

http://grab.by/MkNI
# At the MinkContext line 2920, this is the following code, surely not taking into account the possibility to give 2 ≠ indexes for entities :

/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/MinkContext.php

  /**
     \* Gets the identifier of an entity.
     \* The returned value is always an array of identifier values. If the entity
     \* has a composite identifier then the identifier values are in the same
     \* order as the identifier field names as returned by ClassMetadata#getIdentifierFieldNames().
     *
     \* @param object $entity
     *
     \* @return array The identifier values.
     */
    public function getEntityIdentifier($entity)
    {
        return $this->entityIdentifiers[spl_object_hash($entity)];
    }

**Comment by alexislefebvre** [comment]
Is the problem still present?

**Comment by talbotseb** [comment]
@alexislefebvre : no Behat tests are covering the double blog process, it should be done, i'll create another ticket.
