### ISSUE TITLE
Improve templates list

### ISSUE THREAD

**Issue by lenybernard** [Victoire/victoire#329]
The template list is a mess today, we need to improve it:
![screen shot 2016-02-09 at 14 36 27](https://cloud.githubusercontent.com/assets/618536/12917619/ab895db8-cf3a-11e5-8630-c25ec0e81735.png)
- [ ] Don't use `ol` markup for the list but prefer something like the sitemap
- [ ] Use BackendName property instead of name for the BusinessTemplates

**Comment by LoicGoyet** [comment]
was redesigned with the 2.3 update
