### ISSUE TITLE
[Blog] Fix the URL & title edition system

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#332]
As any blog article is a Business Virtual Page, its properties are stored in two different tables in the DataBase : `vic_article` & `vic_view`

When you edit the name of an article or its URL, it affects only the `vic_article` table and not the `vic_view`
This can generate link errors and affects the coherence of the page information : 

- The breadcrumb and page title are based on the `vic_view` table
- The title of the article is based on the `vic_article` table

**Comment by Charlie-Lucas** [comment]
Close in pull Request [398](https://github.com/Victoire/victoire/pull/398)
