### ISSUE TITLE
[BLOG] At deletion, a blog post causes troubles

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#364]
After the deletion of a blog post, only the view is deleted, but not the post in DataBase.
So Victoire tries to render a business page that doesn't exist.

That impacts other posts and widget : 
- on their ViewCSS
- on widgets where the deleted article figures such as ArticleNav Widget

**Comment by talbotseb** [comment]
@paulandrieux is that fixed with the last blog refactor made by @Charlie-Lucas ?

**Comment by paulandrieux** [comment]
The Article is not deleted but it is passed in "visibleOnFront" false, so the ArticleTemplate has no access to it. I close the issue
