### ISSUE TITLE
Generate a vic_link to a page in another locale (than current)

### ISSUE THREAD

**Issue by lenybernard** [Victoire/victoire#367]
It's possible to create a link to an internal page:
![screen shot 2016-03-30 at 23 59 14](https://cloud.githubusercontent.com/assets/618536/14158965/7958b6ac-f6d3-11e5-9689-fa1d62fc4d92.png)
But the generated link is wrong while it stays in the current locale.
![screen shot 2016-03-31 at 00 00 05](https://cloud.githubusercontent.com/assets/618536/14158977/93f218c8-f6d3-11e5-9815-2ab369a0b08f.png)

This issue seems to be related to https://github.com/Atlantic18/DoctrineExtensions/issues/1560

**Comment by talbotseb** [comment]
Is it still the case with the 1.6 Version ?

**Comment by lenybernard** [comment]
nope you're right
