### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by speeeeeed2006** [Victoire/victoire#390]
I try to add victoire to my project but I can't 
I used : 
composer require victoire/victoire
but I have some error: 
`victoire/victoire 1.5.0 requires doctrine/data-fixtures 1.1.x-dev -> satisfiable by doctrine/data-fixtures[1.1.x-dev] but these conflict with your requirements or minimum-stability.`
when I changed the stability requirment 
```
- victoire/victoire 1.6.x-dev requires doctrine/orm v2.5.2 -> satisfiable by doctrine/orm[v2.5.2] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 1.6.x-dev requires doctrine/orm v2.5.2 -> satisfiable by doctrine/orm[v2.5.2] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 1.5.x-dev requires doctrine/orm v2.5.2 -> satisfiable by doctrine/orm[v2.5.2] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 1.5.0 requires doctrine/orm v2.5.2 -> satisfiable by doctrine/orm[v2.5.2] but these conflict with your requirements or minimum-stability.
    - Installation request for victoire/victoire ^1.5 -> satisfiable by victoire/victoire[1.5.0, 1.5.x-dev, 1.6.x-dev].
```

**Comment by lenybernard** [comment]
Hello,

Can you please paste your entire composer.json please ?

**Comment by speeeeeed2006** [comment]
{
    "name": "*************",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.5.3",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "dev-master",
        "doctrine/doctrine-fixtures-bundle": "~2.3",
        "symfony/assetic-bundle": "^2.8",
        "friendsofsymfony/rest-bundle": "~1.7.8",
        "jms/serializer-bundle" : "dev-master",
        "guzzlehttp/guzzle" : "dev-master",
        "csa/guzzle-bundle" : "dev-master",
        "hwi/oauth-bundle" : "0.4.*@dev",
        "thephalcons/amazon-webservices-bundle": ">=2.1",
        "egulias/email-validator": "dev-master"
    },
    "require-dev": {
        "sensio/generator-bundle": "~3.0",
        "symfony/phpunit-bridge": "~2.7"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "platform": {
            "php": "5.6.16"
        }
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}

**Comment by lenybernard** [comment]
If you want to have a first nice look of victoire, you can just clone the https://github.com/Victoire/victoire repo, run `composer install` and run (in a row or each line individually) the https://github.com/Victoire/victoire/blob/master/Tests/test.sh script which will setup the [Functional project](https://github.com/Victoire/victoire/tree/master/Tests/Functionnal) and run the behat test suites.

Then, for your project, I suggest you to have a look on the victoire's composer.json file which will give you the external dependencies it does need : https://github.com/Victoire/victoire/blob/master/composer.json#L43, then you'll be able to merge with your needs.

Tell me if you're still blocked to setup victoire, also we'll take some time in a couple of days to update the https://github.com/Victoire/demo repository.
