### ISSUE TITLE
[1.6] When I delete a blog article, I'm redirected to a 404

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#394]
I used a multilingual website, with Quantums (or CustomContent).
I created a blog article in the EN version but deleted it as I wanted to write it under the FR version.
At deletion, i've been redirected to a 404 (with the url www.www.com/en/articles instead of www.www.com/fr/news) and all the EN version of the website was 404.

**Comment by paulandrieux** [comment]
By now, if a blog is configured for several locales you cannot create an article just in one locale, you have to create all locales in a row. 
I think Victoire evolved since this bug, is it always up to date ?
