### ISSUE TITLE
The FontAwesomePicker icons aren't persited

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#418]
On several widgets (form, newsletter, button), when I create the widget and choose a FontAwesome Icon, it is ok.
Once I edit the widget for any modification, the icon has disappeared. It should be persisted.

Other issue linked to FontAwesome : #414

**Comment by lenybernard** [comment]
is it still relevant with this commit: https://github.com/Victoire/victoire/commit/ee4d717380990ba3f3cc3c11125fec617db2eca4#diff-932022429b6eea9fe1a95e6a4a0f7d48R740
