### ISSUE TITLE
[Insight] Deprecated class usage found

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#421]
**[in Bundle/TwigBundle/Controller/ExceptionController.php, line 38](https://github.com/Victoire/victoire/blob/ff0d9e58ab63a26e121379387ee00c9b88c5cef3/Bundle/TwigBundle/Controller/ExceptionController.php#L38)**

> The `Symfony\Component\HttpKernel\Exception\FlattenException` class has been deprecated in Symfony 2.3. Use the `Symfony\Component\Debug\Exception\FlattenException` class instead.

``` php
     *
     * @throws \InvalidArgumentException When the exception template does not exist
     *
     * @return Response
     */
    public function showAction(Request $request, FlattenException $exception, DebugLoggerInterface $logger = null, $_format = 'html')
    {
        $currentContent = $this->getAndCleanOutputBuffering($request->headers->get('X-Php-Ob-Level', -1));
        $code = $exception->getStatusCode();

        //get request extension
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d5307bf2-eac4-43db-bd49-dd9e85e360a5/analyses/852)_

**Comment by lenybernard** [comment]
Actually, as we are not yet in Symfony v3 and ExceptionController extends Symfony\Bundle\TwigBundle\Controller\ExceptionController which still use `Symfony\Component\HttpKernel\Exception\FlattenException`, replacing deprecated use by `Symfony\Component\Debug\Exception\FlattenException` is not possible as it would break inheritance.

**Comment by alexislefebvre** [comment]
It has been fixed in https://github.com/Victoire/victoire/commit/c5140929d06a439b9edc4c95678f6d918c9918ce#diff-6d859924144226ef18808f1be1d1a3b6L10
