### ISSUE TITLE
Impossible to delete a widget inherited from a template

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#498]
When on a normal page I try to delete a widget that belongs to a template I have a  [500 Error](https://infinit.io/_/t2T7vRB)

**Comment by paulandrieux** [comment]
The error occurs when a widget is deleted from a template and this widget was overwrited in a child.
In this case, we should change the action of the overwriting widget to "create" and set to null the "replaced_id" column.
See WidgetMapManager:108 (delete action)
