### ISSUE TITLE
Bug install, EntityProxy' does not have a method 'getArticle'

### ISSUE THREAD

**Issue by mantis91** [Victoire/victoire#553]
url = http://localhost/myVictoire/web/app_dev.php/login

Suite à l'installation, j'ai le message suivant : 

ContextErrorException in BaseEntityProxy.php line 59: 
Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Proxies\__CG__\Victoire\Bundle\CoreBundle\Entity\EntityProxy' does not have a method 'getArticle'

Quel serait l'origine de cette erreur selon vous ?

**Comment by paulandrieux** [comment]
The EntityProxy is generated when the cache is cleared, try to execute `php bin/console cache:clear --env=dev`
If you use APC, reload your apache server too.

**Comment by mantis91** [comment]
Petite précision, j'ai installé Victoire demo (standard-project), "https://github.com/Victoire/demo/blob/master/README.md"

l'erreur apparait dès la saisie de cette commande : "php bin/console victoire:generate:view-cache"

Et sur la route "http://localhost/victoireDemo/web/app_dev.php/login" l'aerreur apparait aussi.

j'ai bien clear le cache, avec la commande "php bin/console cache:clear --env=dev" et physiquement dans le dossier app/cache.

Sinon je suis sur un environnement windows, WAMP.

Si quelqu'un a une idée.


Sinon j'ai aussi fais un essai avec "https://github.com/Victoire/standard-edition" mais à l'installation du vendor avec composer, j'ai de nombreux problème de dépendances, j'hésite à les corriger, si le problème viens d'ailleurs.

Merci

**Comment by paulandrieux** [comment]
la demo et la standard edition ne sont pas activement maintenues, la version de victoire up do date est la 1.7, tu peux donc essayer de partir de la standard edition en changeant le composer.json pour "victoire/victoire": "1.7.x-dev"

**Comment by lenybernard** [comment]
Please, try to speak english here to be understood by everyone.

**Comment by lenybernard** [comment]
Hello @mantis91, I've just updated the https://github.com/victoire/standard-edition, you can retry, it should work now.
