### ISSUE TITLE
A linkType in a second quantum does not work

### ISSUE THREAD

**Issue by lenybernard** [Victoire/victoire#590]
Given I have a widget button created
And I go in edit mode
And I click on the widget
And I see an edit modal
Then I can add a new quantum by clicking on the + button
![screen shot 2016-08-26 at 17 51 31](https://cloud.githubusercontent.com/assets/618536/18011506/c37a1f80-6bb5-11e6-9e17-7adb54f568ca.png)
And I can start to define a new Button
When I change the linkType[type] by selecting `viewReference` (aka page)
Then the form should be reloaded with the viewReferences list

There is actually 2 bugs:

- [ ] For a new widget (only), the form does not reload when the select is changed
- [x] For an existing widget (already persisted), the widget is reloaded but seems to show `Route` and `RouteParameters` even if the linkType is not Route which in this case, this is what we expect.

**Comment by paulandrieux** [comment]
the first bug was already fixed
