### ISSUE TITLE
Missing use statement should be avoided in BlogController.php : is this valid

### ISSUE THREAD

**Issue by lenybernard** [Victoire/victoire#60]
First observation :

**[in Bundle/BlogBundle/Controller/BlogController.php, line 179](https://github.com/Victoire/victoire/blob/48cbda3bdb3005abe826cba428244e521b85a7bf/Bundle/BlogBundle/Controller/BlogController.php#L179)**

> The `BusinessEntityPagePattern` class resolves to the following class: `Victoire\Bundle\BusinessEntityPageBundle\Entity\BusinessEntityPagePattern`.
Did you forget to add a corresponding use statement?

```php
        $entityManager = $this->getDoctrine()->getManager();
        $form = $this->createForm($this->getPageCategoryType(), $blog);
        $businessProperties = array();

        //if the page is a business entity page
        if ($blog instanceof BusinessEntityPagePattern) {
            //we can use the business entity properties on the seo
            $businessEntity = $this->get('victoire_core.helper.business_entity_helper')->findById($blog->getBusinessEntityName());
            $businessProperties = $businessEntity->getBusinessPropertiesByType('seoable');
        }

```

Second observation: 

is this usefull ? this not make sense for me and i wonder why you did this, can you explane me ?

**Comment by lenybernard** [comment]
@Charlie-Lucas I will remove this check unless you tell me why you did this.

**Comment by Charlie-Lucas** [comment]
@lenybernard this come from the parent controller.

**Comment by lenybernard** [comment]
and... what do you plan to do ?
