### ISSUE TITLE
[WidgetMenu] Improve the drag & drop tool

### ISSUE THREAD

**Issue by estelleprim** [Victoire/victoire#654]
Improve the fluidity of the widget menu -> make it more intuitive.
- For example, the menu could be drag & dropable so we can change easily the hierarchy of the elements.
- Also to improve the visibility of the menu, we could only let visible the title of the category and make the others elements (links, url, etc.) only visible in a fanfold (=accordéon) so the user can have a vision of his menu at a glance.
- Currently it's not really pleasant to search a page in all the pages of the website to make it a link. May be we could range the pages by category (if it belongs to "Products" or to "Who we are", ect.) or join a research function => see #591

**Comment by talbotseb** [comment]
see https://github.com/FriendsOfVictoire/WidgetMenuBundle/issues/13
