### ISSUE TITLE
I can't create or edit article when author avatar link is broken

### ISSUE THREAD

**Issue by BFoucher** [Victoire/victoire#672]
## Description
When i want to create or edit an article, if selected author avatar is missing (missing file, not null !), modal close and re open without error message. 

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |  |
| Blog           |  &#10004;        | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |          | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |

**Comment by paulandrieux** [comment]
Victoire does not come with an avatar for users. The only avatar used is from gravatar.
This issue seems related to your project implementation.
