### ISSUE TITLE
[SEO Victoire : SItemap] Check the box "URL indexée" by default

### ISSUE THREAD

**Issue by estelleprim** [Victoire/victoire#693]
Once a page is created, the default SEO parameters used are :
- page indexed : 0
- page priority : 0

it should be :
- page indexed :1
- page priority : 0.5

**Comment by talbotseb** [comment]
@gregumo check if the index parameter is active towards the bots - i'm not sur that it is used so far.

**Comment by gregumo** [comment]
Fix in PR #839
