### ISSUE TITLE
Integrates in BlogBundle the choice tree form type

### ISSUE THREAD

**Issue by lenybernard** [Victoire/victoire#698]
## Description
The infinite/form-bundle maintainers won't merge the PR @Charlie-Lucas did:
https://github.com/infinite-networks/InfiniteFormBundle/pull/46 and we're stucked with the @Charlie-Lucas 's fork which isn't compatible with Symfony3

## Resolution Ideas
Integrates the PR in the BlogBundle (I guess ?)

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |  |
| Blog           |   &#10004;       | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |          | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           | &#10004; | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |

**Comment by alexislefebvre** [comment]
@lenybernard Is it possible to create a Bundle that extend infinite/form-bundle and add the choice_tree?

**Comment by lenybernard** [comment]
We won't do this as the code is really ugly.
