### ISSUE TITLE
Insert dribbble option inside the social links widget

### ISSUE THREAD

**Issue by clekos** [Victoire/victoire#699]

**Comment by lenybernard** [comment]
As you said, this issue is not related to Victoire but to the social links widget, si please report this issue in the correct repository : https://github.com/FriendsOfVictoire/WidgetSocialButtonsBundle

**Comment by lenybernard** [comment]
Moved to https://github.com/FriendsOfVictoire/WidgetSocialButtonsBundle/issues/10
