### ISSUE TITLE
API mode

### ISSUE THREAD

**Issue by paulandrieux** [Victoire/victoire#721]
Scope
=====
Be able to use data fetched from an API to populate pages and widgets.

Goal
=====
Remove the dependency to Doctrine ORM to handle BusinessEntities.
We want to be able to use the plenty of data APIs existing on the web to display contents on Victoire websites.

Product area
===========
[BusinessEntity] [Widget] [BusinessPage]

**Comment by alexislefebvre** [comment]
The API mode was merged in #812.
