### ISSUE TITLE
When I create a quantum on a template, the new widget created is wrongly set

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#732]
- I am on a template
- I edit a widget and create a quantum with criteria etc ...
- A new widget is created and answers the criteria
- BUT the previous widget based on the default criteria is not visible

- In the DB, the widgets are setted with different widget_map_id instead of using the same one.

Resolution : directly in the DB :

- The newly generated widget_map_id is deleted
- The widget_map_id of the new vic_widget has to be the same one than the original widget

**Comment by BFoucher** [comment]
This issue not appears when you edit the widget on the template but when you edit widget in children page of this template. 

- I edit the widget
- I follow "edit the original widget"
- I create two new quantum

When i save, the 2 quantum are created with a new widget_map
