### ISSUE TITLE
[UI][UX] Add a preview mode in the "Style" tab

### ISSUE THREAD

**Issue by alexislefebvre** [Victoire/victoire#755]
## Description
When I edit a widget's style, I would like to preview it before saving it.

## Resolution Ideas
- Add a *preview* button that show the widget in a modal dialog
- Display the widget in a box next to the form that will display the widget and apply style options in real-time

**Comment by paulandrieux** [comment]
In a next verson, it is scheduled that the style form should not appear in a modal but in a tooltip that not hidding the widget itself. 
A preview mode is a great idea but require a lot of work that will be deprecated with this next feature
