### ISSUE TITLE
CSS is broken when I modify a widget from a template

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#762]
- I edit a widget which is part of a template
- I choose to modify the whole template
- I valid the modification
- The page is refreshed
- The style is broken

Either a v-g-v or a Css-hash hack is needed to fix this.

**Comment by gregumo** [comment]
I'll take a look at this.
The expected behaviour is that all Template children's CSS are regenerated with a CRON but if one user need this View before, CSS file must be created on the fly and the page will appear correctly.

**Comment by gregumo** [comment]
On WidgetCssGenerateCommand, we need to regenerate only Views for cssUpToDate = false
