### ISSUE TITLE
"new" template is call to edit a widget 

### ISSUE THREAD

**Issue by Charlie-Lucas** [Victoire/victoire#77]
In WidgetManager->editWidget() :
if It's a Post request method the template which is call is "edit" else is a "new". So we persist or update the form if true.
The issue is if we edit a widget, we dont post any form, the editWidget Action is call but the response is made with the "new" template no the "edit".
I think we must call "new" template only for the creation of the widget, and call "edit" template for update wrong forms and when we want edit a widget.

**Comment by talbotseb** [comment]
@paulandrieux this issue doesn't seem accurate with the evolution of Victoire, could you check and close it please ?

**Comment by alexislefebvre** [comment]
I don't see any bug here. I'm closing this.

If a similar problem is encountered again, feel free to reopen this issue. Thanks.
