### ISSUE TITLE
Add command to fetch assets

### ISSUE THREAD

**Issue by lenybernard** [Victoire/victoire#813]
## Description  

Allow to fetch front dependencies thanks to a command

## Resolution Ideas

A simple command which will run bower install for now

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |  |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |          | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UIBundle | &#10004; | | |

**Comment by alexislefebvre** [comment]
It looks like it has been fixed by #832.

**Comment by gregumo** [comment]
Yes it does. Thanks !
