### ISSUE TITLE
Impossible to edit a page priority through Victoire's Sitemap

### ISSUE THREAD

**Issue by talbotseb** [Victoire/victoire#820]
## Description
While I am editing pages through Victoire's sitemap, I tried to edit the page priority via the select menu.
When I change the priority value, I refresh the page and the new value shown is not the one I set, meanwhile the value within the SEO advanced parameters is still the one from before the change.

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |          | Page           |          |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo            | &#10004; |
| BusinessPage   |          | Sitemap       | &#10004; |
| Core           |          | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |

**Comment by gregumo** [comment]
Fix in PR #839
