### ISSUE TITLE
Widget slot not displayed on screen

### ISSUE THREAD

**Issue by naomiHauret** [Victoire/victoire#836]
## Description
Creating two or more cms_slot_widgets() that contains underscores ( _ ) or dashes ( - ) cause them to not being displayed on screen.

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |       | Page           |  |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |          | Template       |    &#10004;         |
| Criteria       |          | Twig           |   &#10004;         |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UI             |     &#10004;       |                |          |

**Comment by gregumo** [comment]
Actually it does work with underscores : for example, we use use the slotId "main_content" in Victoire Core layout.
The problem with dashes is not related to Victoire but to twig functions which doesn't work with parameters containing dashes. The error occurs before Victoire's TwigExtension so we can't do anything about it.
Thx but I close this issue.
