### ISSUE TITLE
bug background-image - subdirectory

### ISSUE THREAD

**Issue by Akiletour** [Victoire/victoire#84]
for example here : 
https://github.com/Victoire/victoire/blob/master/Bundle/CoreBundle/Resources/style/less/bricks/vic-images.less#L3

You called directly "/bundles/victoirecore/images/sprite@2x.png", but if our project is in a subdirectory, this sprite returns 404.

But I don't know how to fix this. Maybe with a base href and remove the slash in css files ?

sorry for my English which comes from the depths of the galaxy.

**Comment by paulandrieux** [comment]
Fixed by https://github.com/Victoire/victoire/pull/83

**Comment by lenybernard** [comment]
No @paulandrieux, I don't think @Akiletour was talking about the PR #83.

**Comment by Akiletour** [comment]
Indeed, i was talking in a LESS file, if we have the project in a subdirectory, (mywebsite.com/victoire/web/...), the ressources background-image for example call directly (/bundles/....), so the ressources return 404 (mywebsite.com/bundles/....) instead of mywebsite.com/victoire/web/bundles/...

**Comment by lenybernard** [comment]
@Akiletour : I think you should read the [web_server_configuration.html](http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html) article to setup a proper basic symfony project to get rid of this issue which doesn't seems to be related to Victoire.
