### ISSUE TITLE
Some troubles when I attempt to setup Victoire

### ISSUE THREAD

**Issue by Yoann-TYT** [Victoire/victoire#946]
## Description
Hello !

First of all, I wanted to tell you that when @BFoucher  explained me your CMS Victoire, last thursday during the #sfpot, I was quite excited to discover it. A CMS that would associate the expected features of a CMS with our custom logic would be so awesome :)

So, I attempted to test it, but I met some troubles… :-(

I needed to adapt your setup.md. ( Because, at the beginning, I just had a « white screen » ). If you want, I can make a PR :)
https://github.com/Yoann-TYT/victoire/commit/7155aaca007804d9f96f0f4db28cffbc476dd99c

First trouble, a javascript error says that this.drop is a null element… 
`
,{key:"dropAnchors",get:function(){return Array.prototype.slice.call(this.drop.querySelectorAll("a"))}
`

So, a lot of javascript buttons doesn’t work.

Some errors on Media Library as : 

> Expected argument of type "string", "Victoire\Bundle\MediaBundle\Form\RemoteSlide\RemoteSlideType" given
Or …. 
> The "replace" filter expects an array or "Traversable" as replace values, got "string".

So, can you tell me what version of Victoire should I use to test your CMS ? :)

This is my composer info

I use PHP 7.1.3 and its built-in web server

>a2lix/translation-form-bundle        2.1.2   Translate your doctrine objects easily with some helps
behat/transliterator                 v1.2.0  String transliterator
composer/ca-bundle                   1.0.7   Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
doctrine/annotations                 v1.4.0  Docblock Annotations Parser
doctrine/cache                       v1.6.1  Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.4.0  Collections Abstraction library
doctrine/common                      v2.7.2  Common Library for Doctrine projects
doctrine/data-fixtures               v1.2.2  Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        v2.5.12 Database Abstraction Layer
doctrine/doctrine-bundle             1.6.8   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0   Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle    2.3.0   Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle  v1.2.1  Symfony DoctrineMigrationsBundle
doctrine/inflector                   v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  v1.5.0  Database Schema migrations using Doctrine DBAL
doctrine/orm                         v2.5.6  Object-Relational-Mapper for PHP
friendsofsymfony/jsrouting-bundle    1.6.0   A pretty nice way to expose your Symfony2 routing to client applications.
friendsofsymfony/user-bundle         v2.0.1  Symfony FOSUserBundle
fzaninotto/faker                     v1.6.0  Faker is a PHP library that generates fake data for you.
gedmo/doctrine-extensions            v2.4.29 Doctrine2 behavioral extensions
imagine/imagine                      v0.6.3  Image processing for PHP 5.3
incenteev/composer-parameter-handler v2.1.2  Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
jms/metadata                         1.6.0   Class/method/property metadata management in PHP
jms/parser-lib                       1.0.0   A library for easily creating recursive-descent parsers.
jms/serializer                       1.7.1   Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                1.5.0   Allows you to easily serialize, and deserialize data of any complexity
knplabs/doctrine-behaviors           1.4.0   Doctrine2 behavior traits
knplabs/gaufrette                    v0.1.9  PHP5 library that provides a filesystem abstraction layer
knplabs/knp-menu                     2.2.0   An object oriented menu library
knplabs/knp-menu-bundle              2.1.3   This bundle provides an integration of the KnpMenu library
kriswallsmith/assetic                v1.4.0  Asset Management for PHP
liip/imagine-bundle                  1.8.0   This bundle provides an image manipulation abstraction toolkit for Symfony-based projects.
monolog/monolog                      1.23.0  Sends your logs to files, sockets, inboxes, databases and various web services
nelmio/alice                         v2.3.1  Expressive fixtures generator
ocramius/package-versions            1.1.2   Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager               2.1.1   A library providing utilities to generate, instantiate and generally operate with Object Proxies
paragonie/random_compat              v2.0.10 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7

## Resolution Ideas

It should be just a version problem, no ?

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           | &#10004; |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |   &#10004;       | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UI             |    &#10004;      |                |          |

**Comment by lenybernard** [comment]
Hello,
Thank you for your try. I took some time this evening to test the `setup.md` and there were indeed some forgets, I've updated the documentation: https://github.com/Victoire/victoire/blob/2.3/doc/setup.md.

We prepare a tutorial and the first step is to deal with the setup, can you compare your code with this: https://github.com/Victoire/tutorial/tree/0744813baba719453e0673611c53d1d511133e65

Can you try with this code and tell me if you do still have the same javascript issues ? AFIK I don't remember such issue.

Plus, for the `knp_menu` config and the `role_hierarchy`. They are normally loaded by the https://github.com/Victoire/victoire/blob/2.3/Bundle/CoreBundle/Resources/config/security.yml which is loaded by https://github.com/Victoire/victoire/blob/2.3/Bundle/CoreBundle/Resources/config/config.yml which need to be loaded like explained in the doc:

```
imports:
    - { resource: "@VictoireCoreBundle/Resources/config/config.yml" }
    - { resource: "@VictoireTwigBundle/Resources/config/config.yml" }
```

I bet you forgot this step, right ?

**Comment by Yoann-TYT** [comment]
I did a stupid error...

`
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

[...]

imports:
    - { resource: "@VictoireCoreBundle/Resources/config/config.yml" }
    - { resource: "@VictoireTwigBundle/Resources/config/config.yml" }
`

So, the second block wasn't loaded... -_-' 
Everything work successfully, now is time to discover Victoire :)

Thanks !
