### ISSUE TITLE
Can't delete widgets

### ISSUE THREAD

**Issue by robinstraub** [Victoire/victoire#949]
## Description
Unable to delete UI elements once they are create (e.g. a page, a widget ...). The loading animation is infinite and nothing happens.

## Resolution Ideas
at [https://github.com/Victoire/victoire/blob/2.3/Bundle/CoreBundle/Resources/views/UI/confirm.html.twig#L60](https://github.com/Victoire/victoire/blob/2.3/Bundle/CoreBundle/Resources/views/UI/confirm.html.twig#L60) the variable "type" is not defined, leading to a twig error. Error was not present in the master branch as the type variable was passed from the controller, howwever on 2.3 it is no longer the case.

replacing `{% if type == "form" %}` by `{% if type is defined and type == "form" %}` solved the issue in my test environment

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |          | Page           |          |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           | &#10004; | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |  &#10004;  |
| Media          |          | WidgetMap      |          |
| UI             |          |                |          |

**Comment by alexislefebvre** [comment]
Thanks for your report. Could you please submit a PR with your patch?

**Comment by lenybernard** [comment]
Hello @robinstraub,
I understand the problem, you need to replace `type` by `app.request.get('type')`.

The second good news is you don't need to add test to protect this feature as this already exists: https://github.com/Victoire/victoire/blob/2.3/Tests/Features/Widget/delete.feature

But there is another thing to do, the test don't fail but it should and the reason is that `twig` in test env is configured to silent unknown variables (`strict_variables`). We need to force the `strict_variable` to true.

Tell me if you need help.

**Comment by robinstraub** [comment]
Thanks for the news @lenybernard 

According to [#951](https://github.com/Victoire/victoire/issues/951) I replaced the symfony version to be able to run the application, however after starting the server I get stuck at the HTTP authentication. Any advice on how to run the app on the 2.3 branch? 

I cannot try to implement the fix you recommand and submit a PR without testing it

**Comment by lenybernard** [comment]
Apparently, you still experience issue with your test env.
It's a bit off topic but what is your selenium version, what is your firefox or chrome version ? According to the browser, what is the versions of your drivers (chromedriver or firefox/gecko) ?

**Comment by robinstraub** [comment]
I use selenium 2.53 as it is the one downloaded with the test.sh script. I downgraded firefox to v46.0.1 to work with the selenium driver, Gecko version is 46.0 according to the browser useragent. 

Are these versions causing issues?

**Comment by robinstraub** [comment]
@lenybernard it was indeed a problem in my test env, I re-updated my firefox version and changed ym geckodriver and the tests run fine now.
